name: 🐞 Bug Report
description: Report a problem with Companion
title: "[Bug]: "
labels: ["bug"]

body:
  - type: checkboxes
    attributes:
      label: Quick check
      options:
        - label: I searched existing issues to make sure this isn’t already reported.
          required: true

  - type: textarea
    attributes:
      label: What happened?
      description: Briefly describe the problem (what you did + what you saw).
      placeholder: "When I click ..., the app ... and shows ..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce (if you know them)
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected result (optional)
      placeholder: "I expected ..."
    validations:
      required: false

  - type: textarea
    attributes:
      label: Environment (optional)
      description: Help us reproduce it. Just fill what you know.
      placeholder: |
        - Companion version:
        - OS (macOS/Windows/Linux + version):
        - CPU (Intel/Apple Silicon):
        - Device/camera model (if relevant):
    validations:
      required: false

  - type: textarea
    attributes:
      label: Logs / screenshots (optional)
      description: Paste logs or drag/drop screenshots here.
    validations:
      required: false
