name: 🚀 Feature request
description: Suggest an idea or improvement for Companion
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: checkboxes
    attributes:
      label: Quick check
      options:
        - label: I searched existing issues to make sure this hasn’t been requested already.
          required: true

  - type: textarea
    attributes:
      label: What problem are you trying to solve?
      description: Describe the problem or limitation you’re running into.
      placeholder: "Right now it’s hard to ..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: What would you like to see?
      description: Describe the feature or improvement you’re proposing.
      placeholder: "It would be great if Companion could ..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Any additional context? (optional)
      description: Screenshots, sketches, examples, or links that help explain the idea.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Thanks for helping make Companion better 🚀
